var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/about/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1h4d1r4._.js")
R.c("server/chunks/ssr/app_data_stories_ts_0a5s_mw._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0iatj70._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12u481u._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ryyel5._.js")
R.c("server/chunks/ssr/node_modules_next_1rt-art._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09b7ugu._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_about_page_actions_0xvgj07.js")
R.m(30250)
module.exports=R.m(30250).exports
