var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/story/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1qwj3ha._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0iatj70._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12u481u._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ryyel5._.js")
R.c("server/chunks/ssr/node_modules_next_1rt-art._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09b7ugu._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/app_story_[slug]_opengraph-image--metadata_0n_e6uy.js")
R.c("server/chunks/ssr/app_data_stories_ts_0a5s_mw._.js")
R.c("server/chunks/ssr/_0pyrdbh._.js")
R.c("server/chunks/ssr/_next-internal_server_app_story_[slug]_page_actions_0320b-u.js")
R.m(32970)
module.exports=R.m(32970).exports
