var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c8bylm._.js")
R.c("server/chunks/ssr/app_page_tsx_1noek_q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/app_data_stories_ts_0a5s_mw._.js")
R.c("server/chunks/ssr/_01h-p29._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0iatj70._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12u481u._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ryyel5._.js")
R.c("server/chunks/ssr/node_modules_next_1rt-art._.js")
R.c("server/chunks/ssr/_034cmi9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_0hhsz1j.js")
R.m(70834)
module.exports=R.m(70834).exports
